// ============================================================
//  TradeOS v5 — Thesis starter templates (Phase 2A)
//  Pick a thesis type and the four fields fill with a real first
//  draft (80-90% done). The chips are complete sentences you can
//  append to the thesis to strengthen it. Template only, no AI.
//  Bilingual content lives here (not the UI dictionary).
//  Voice: a real investor's own notes. No em dashes, no MBA-speak.
// ============================================================

export type ThesisType =
  | 'growth' | 'compounder' | 'value' | 'dividend' | 'turnaround'
  | 'speculation' | 'etf' | 'cyclical' | 'ai' | 'smallcap'

export interface ThesisTemplate {
  label:        string
  thesis:       string
  bullCase:     string
  bearCase:     string
  invalidation: string
  chips:        string[]   // complete sentences, appended on click
}

export const THESIS_TYPES: ThesisType[] = [
  'growth', 'compounder', 'value', 'dividend', 'turnaround',
  'speculation', 'etf', 'cyclical', 'ai', 'smallcap',
]

const EN: Record<ThesisType, ThesisTemplate> = {
  growth: {
    label: 'Growth',
    thesis: 'The company still has plenty of room to grow revenue over the next few years, and it is taking share in a large market.',
    bullCase: 'Revenue keeps growing faster than the market expects, and the stock re-rates higher as it does.',
    bearCase: 'Growth slows toward the market average and investors stop paying a premium for it.',
    invalidation: 'Revenue growth stalls for two or three quarters in a row with no clear reason.',
    chips: [
      'The market it sells into is large and still growing.',
      'It is steadily taking share from its competitors.',
      'New products should open up fresh revenue.',
      'It can keep expanding into new regions.',
      'As it grows, more of each new dollar drops to profit.',
      'A large part of the revenue repeats every year.',
      'The founder still runs it and owns a big stake.',
      'It has the pricing power to raise prices without losing customers.',
    ],
  },
  compounder: {
    label: 'Compounder',
    thesis: 'This is a high-quality business I want to own for years and just let grow, because it puts its cash back to work at high returns.',
    bullCase: 'It keeps growing steadily year after year, so the position quietly becomes worth more over time.',
    bearCase: 'The returns it earns on cash fade as it gets bigger, and the steady growth slows down.',
    invalidation: 'Return on capital drops sharply, or management starts spending cash poorly.',
    chips: [
      'It is hard for competitors to take this business away.',
      'It earns high returns on the cash it puts to work.',
      'It still has years of growth ahead of it.',
      'Management reinvests cash at good rates of return.',
      'It can raise prices a little every year.',
      'Most of the revenue repeats, so results are predictable.',
      'It carries very little debt.',
      'It buys back its own shares over time.',
    ],
  },
  value: {
    label: 'Value',
    thesis: 'The stock looks clearly cheaper than what the business is actually worth today, so I am buying the gap.',
    bullCase: 'The market notices the value and the price moves up to meet it, or the company returns cash to get there.',
    bearCase: 'It stays cheap because the business keeps getting weaker, so it was cheap for a reason.',
    invalidation: 'Earnings and cash flow keep falling, which means the low price is deserved.',
    chips: [
      'It trades for less than the assets on its books are worth.',
      'The earnings multiple is low versus its own history.',
      'There is a lot of cash on the balance sheet.',
      'The company is buying back its own shares.',
      'Insiders have been buying the stock themselves.',
      'The problem weighing on it looks temporary.',
      'It generates a high free cash flow yield at this price.',
      'It could be an attractive takeover target.',
    ],
  },
  dividend: {
    label: 'Dividend',
    thesis: 'I hold this mainly for a steady, growing dividend that the company can clearly afford to keep paying.',
    bullCase: 'The dividend keeps growing and stays well covered by cash flow, so I get paid to wait.',
    bearCase: 'Cash flow weakens and the dividend starts to look stretched or at risk.',
    invalidation: 'The company cuts or suspends the dividend.',
    chips: [
      'The dividend is well covered by free cash flow.',
      'It has paid and raised the dividend for many years.',
      'The payout ratio is low, leaving room to keep growing it.',
      'The underlying business is stable and defensive.',
      'The balance sheet is strong enough to protect the payout.',
      'It holds up well even in a weak economy.',
      'It also returns cash through buybacks.',
      'Its cash flow is steady and predictable.',
    ],
  },
  turnaround: {
    label: 'Turnaround',
    thesis: 'This is a beaten-down business with a real chance to recover, and I think the worst is close to behind it.',
    bullCase: 'The fix works, margins and profits start coming back, and the stock re-rates as confidence returns.',
    bearCase: 'The recovery never really arrives and the business keeps sliding.',
    invalidation: 'Several quarters pass with no sign of improvement in the numbers.',
    chips: [
      'New management is in place and focused on the fix.',
      'Costs are being cut and weak units sold off.',
      'Debt is coming down quarter by quarter.',
      'A new product cycle should help demand recover.',
      'Most of the bad news already looks priced in.',
      'Insiders have started buying the stock.',
      'Margins appear to be bottoming out.',
      'Expectations are so low that small wins could move the stock.',
    ],
  },
  speculation: {
    label: 'Speculation',
    thesis: 'This is a small, high-risk bet that one specific thing goes right, and I am sizing it so a loss will not hurt much.',
    bullCase: 'That one thing happens and the stock re-rates sharply higher.',
    bearCase: 'It does not play out and most of the money I put in is at risk.',
    invalidation: 'It becomes clear the bet is not going to work, or the catalyst gets pushed out indefinitely.',
    chips: [
      'This rides on a single, clear catalyst playing out.',
      'I am keeping the position small on purpose.',
      'If it works, the upside is very large.',
      'If it fails, this could go close to zero.',
      'The company is still early and unproven.',
      'It may need to raise more money to survive.',
      'A lot of the stock is sold short, which could squeeze.',
      'I will cut it quickly if the story breaks.',
    ],
  },
  etf: {
    label: 'ETF',
    thesis: 'I own this fund for broad, low-cost exposure to a market or theme, so I do not have to pick single winners.',
    bullCase: 'The whole basket drifts higher over time and I capture the average return without single-stock risk.',
    bearCase: 'The market or theme stays flat or falls, and the fund drops with it.',
    invalidation: 'The long-term reason I bought the theme no longer holds, or fees and tracking get too high.',
    chips: [
      'It gives me broad exposure without picking single stocks.',
      'The fees are very low.',
      'It simply tracks an index, so there is no manager risk.',
      'I treat it as a core, long-term holding.',
      'I can add to it steadily over time.',
      'It covers a whole sector or theme in one buy.',
      'It is liquid and easy to trade.',
      'It rebalances itself so I do not have to.',
    ],
  },
  cyclical: {
    label: 'Cyclical',
    thesis: 'I am buying this cyclical business near the low point of its cycle, expecting demand and prices to recover.',
    bullCase: 'The cycle turns up, demand and prices recover, and earnings jump off a low base.',
    bearCase: 'The downturn lasts longer than expected and earnings stay depressed.',
    invalidation: 'The cycle keeps getting worse, or it turns out to be a structural decline rather than a cycle.',
    chips: [
      'I am buying near what looks like the low point of the cycle.',
      'Demand and prices should recover as the cycle turns.',
      'Inventories are low, which usually comes before a recovery.',
      'When the cycle turns, profits jump off a low base.',
      'It looks cheap against normal mid-cycle earnings.',
      'Supply is tightening across the industry.',
      'The balance sheet is strong enough to wait out the downturn.',
      'Margins look like they are bottoming.',
    ],
  },
  ai: {
    label: 'AI Theme',
    thesis: 'I own this as a way to play the shift toward AI, where I think spending and adoption keep rising for years.',
    bullCase: 'AI demand keeps growing and this company captures a real, growing share of that spending.',
    bearCase: 'AI spending slows or commoditizes, and this company turns out not to be a key winner.',
    invalidation: 'The company loses its edge in AI, or the AI demand it depends on clearly rolls over.',
    chips: [
      'Spending on AI keeps rising across the industry.',
      'This company earns real revenue from AI, not just hype.',
      'It is a key supplier that AI buildouts depend on.',
      'It owns data or tools that are hard to replicate.',
      'Demand for its compute or software keeps growing.',
      'Customers find it hard to switch away from it.',
      'It is an early leader in its part of the AI stack.',
      'This is a long-term shift, not a short fad.',
    ],
  },
  smallcap: {
    label: 'Small Cap',
    thesis: 'This is a small company that is still under the radar, and I think it can grow a lot before the market pays attention.',
    bullCase: 'It keeps executing and growing, and the stock re-rates as more investors discover it.',
    bearCase: 'Growth disappoints, or being small and thinly traded makes the stock swing hard against me.',
    invalidation: 'Growth stalls, the balance sheet gets stretched, or the original reason to own it breaks.',
    chips: [
      'It is small and still flies under most investors’ radar.',
      'The founder runs it and owns a large stake.',
      'It has plenty of room to grow from a small base.',
      'Almost no analysts cover it yet.',
      'It could become an acquisition target.',
      'It is a leader in its small niche.',
      'It funds its own growth without needing outside money.',
      'Profits are being reinvested back into the business.',
    ],
  },
}

const ZH: Record<ThesisType, ThesisTemplate> = {
  growth: {
    label: '成长',
    thesis: '这家公司未来几年还有很大的营收增长空间,而且正在一个大市场里抢份额。',
    bullCase: '营收持续增长得比市场预期更快,股价也随之上修。',
    bearCase: '增长放缓到接近行业平均,投资者不再愿意为它付溢价。',
    invalidation: '营收连续两三个季度不再增长,而且找不到明确原因。',
    chips: [
      '它所在的市场很大,而且还在增长。',
      '它正稳步从对手手里抢份额。',
      '新产品有望打开新的收入来源。',
      '它还能继续向新的地区扩张。',
      '规模变大后,每多赚一块钱更多落到利润里。',
      '很大一部分收入每年都会重复。',
      '创始人还在掌舵,而且持有很大股份。',
      '它有定价权,涨价也不会流失客户。',
    ],
  },
  compounder: {
    label: '复利',
    thesis: '这是一门高质量的生意,我想拿很多年、让它慢慢长大,因为它能把现金以高回报再投出去。',
    bullCase: '它年复一年稳定增长,这个仓位会悄悄变得越来越值钱。',
    bearCase: '随着体量变大,它在现金上赚到的回报下降,稳定的增长也放慢。',
    invalidation: '资本回报率大幅下滑,或者管理层开始乱花钱。',
    chips: [
      '对手很难把这门生意抢走。',
      '它把现金再投出去能赚到高回报。',
      '它前面还有很多年的增长。',
      '管理层以不错的回报率把现金再投资。',
      '它每年都能小幅提价。',
      '收入大多重复,业绩可预测。',
      '它几乎没有负债。',
      '它会持续回购自己的股票。',
    ],
  },
  value: {
    label: '价值',
    thesis: '股价明显比这家公司现在实际值的便宜,我买的就是这个差价。',
    bullCase: '市场注意到它的价值,股价向价值靠拢,或公司通过分红回购把价值还给股东。',
    bearCase: '它一直便宜,是因为生意在持续变弱,便宜有便宜的道理。',
    invalidation: '盈利和现金流持续下滑,说明这个低价是应得的。',
    chips: [
      '股价比账面资产的价值还低。',
      '相对自身历史,市盈率处在低位。',
      '资产负债表上有很多现金。',
      '公司正在回购自己的股票。',
      '内部人自己也在买入股票。',
      '压制它的问题看起来是暂时的。',
      '按现价算,它的自由现金流收益率很高。',
      '它可能成为有吸引力的收购对象。',
    ],
  },
  dividend: {
    label: '股息',
    thesis: '持有它主要是为了一份稳定、还在增长、公司明显付得起的股息。',
    bullCase: '股息持续增长,而且被现金流稳稳覆盖,等的过程中我一直有钱拿。',
    bearCase: '现金流走弱,股息开始显得紧张、有被砍的风险。',
    invalidation: '公司削减或暂停了股息。',
    chips: [
      '股息被自由现金流稳稳覆盖。',
      '它已经连续很多年派息并提高股息。',
      '派息率很低,还有继续提高的空间。',
      '底层生意稳定、偏防御。',
      '资产负债表足够强,能保护这份派息。',
      '即便经济疲软,它也撑得住。',
      '它还通过回购把现金还给股东。',
      '它的现金流稳定、可预测。',
    ],
  },
  turnaround: {
    label: '反转',
    thesis: '这是一家被打压的公司,有真实的复苏机会,我认为最糟的阶段快过去了。',
    bullCase: '整改见效,利润率和利润开始回来,信心恢复带动股价重估。',
    bearCase: '复苏始终没真正到来,生意继续往下滑。',
    invalidation: '好几个季度过去,数字上仍看不到改善迹象。',
    chips: [
      '新管理层已经到位,专注于扭转局面。',
      '正在削减成本、卖掉弱业务。',
      '负债在一个季度一个季度地下降。',
      '新的产品周期有望带动需求回升。',
      '大部分坏消息看起来已经反映在股价里。',
      '内部人已经开始买入股票。',
      '利润率看起来正在见底。',
      '市场预期极低,一点小进展就可能推动股价。',
    ],
  },
  speculation: {
    label: '投机',
    thesis: '这是一笔押某件具体事情成真的小额高风险仓位,我控制好仓位,亏了也不至于伤筋动骨。',
    bullCase: '那件事成真,股价快速大幅重估。',
    bearCase: '没成,我投进去的大部分钱都有风险。',
    invalidation: '已经能看出这个赌注成不了,或催化剂被无限期推迟。',
    chips: [
      '它押的是某一个明确催化剂能否兑现。',
      '我刻意只放很小的仓位。',
      '如果成了,上行空间非常大。',
      '如果失败,这笔可能接近归零。',
      '公司还处在早期、未经验证。',
      '它可能需要再融资才能活下去。',
      '很大比例的股票被做空,可能逼空。',
      '一旦逻辑破裂,我会很快止损。',
    ],
  },
  etf: {
    label: 'ETF',
    thesis: '我买这只基金是为了低成本、广泛地暴露在某个市场或主题上,不用去挑单个赢家。',
    bullCase: '整篮子随时间上行,我拿到平均回报,又避开了单只股票的风险。',
    bearCase: '这个市场或主题不涨甚至下跌,基金跟着回落。',
    invalidation: '当初看好这个主题的长期理由不再成立,或费用和跟踪误差变得太高。',
    chips: [
      '它让我获得广泛暴露,不用去挑单只股票。',
      '费用非常低。',
      '它只是跟踪指数,没有基金经理的风险。',
      '我把它当作核心的长期持仓。',
      '我可以分批长期加仓。',
      '一次买入就覆盖整个行业或主题。',
      '它流动性好、买卖方便。',
      '它会自动再平衡,我不用操心。',
    ],
  },
  cyclical: {
    label: '周期',
    thesis: '我在这门周期性生意接近周期低点时买入,预期需求和价格会回升。',
    bullCase: '周期向上,需求和价格回升,利润从低基数上大幅跳升。',
    bearCase: '下行持续的时间比预期更长,利润长期低迷。',
    invalidation: '周期继续恶化,或者发现这其实是结构性衰退、不是周期。',
    chips: [
      '我在看起来是周期低点的位置买入。',
      '随着周期反转,需求和价格应会回升。',
      '库存很低,这通常出现在复苏之前。',
      '周期一旦反转,利润会从低基数大幅跳升。',
      '按正常的中周期盈利看,它很便宜。',
      '整个行业的供给在收紧。',
      '资产负债表够强,能熬过这轮下行。',
      '利润率看起来正在见底。',
    ],
  },
  ai: {
    label: 'AI 主题',
    thesis: '我把它当作押注 AI 大趋势的一种方式,我认为相关投入和普及会持续好几年。',
    bullCase: 'AI 需求持续增长,这家公司在这块支出里拿到真实且不断扩大的份额。',
    bearCase: 'AI 支出放缓或变成同质化竞争,而这家公司其实算不上关键赢家。',
    invalidation: '公司在 AI 上的优势丢失,或它依赖的 AI 需求明显见顶回落。',
    chips: [
      '全行业在 AI 上的投入持续增加。',
      '这家公司从 AI 赚的是真实收入,不是概念。',
      '它是 AI 建设离不开的关键供应商。',
      '它拥有难以复制的数据或工具。',
      '对它的算力或软件的需求持续增长。',
      '客户很难从它这里切换走。',
      '在 AI 这一环里,它是早期领先者。',
      '这是长期的趋势转变,不是短暂的风口。',
    ],
  },
  smallcap: {
    label: '小盘',
    thesis: '这是一家还没被关注到的小公司,我认为它能在市场注意到之前长大很多。',
    bullCase: '它持续把事做成、保持增长,随着更多投资者发现它,股价重估。',
    bearCase: '增长不及预期,或者因为盘子小、成交清淡,股价会剧烈波动反噬我。',
    invalidation: '增长停滞,资产负债表被拉紧,或当初持有的理由不再成立。',
    chips: [
      '它很小,还没被大多数投资者注意到。',
      '创始人在经营,而且持有很大股份。',
      '基数小,成长空间很大。',
      '几乎还没有分析师覆盖它。',
      '它可能成为被收购的对象。',
      '它是这个小细分领域的领头羊。',
      '它靠自己赚的钱供养增长,不用外部融资。',
      '利润正被重新投回业务里。',
    ],
  },
}

export function thesisTemplate(type: ThesisType, lang: 'en' | 'zh'): ThesisTemplate {
  return (lang === 'zh' ? ZH : EN)[type]
}
